### ISSUE TITLE
cannot find DCS Export Scripts Mosquito module

### ISSUE THREAD

**Issue by bwanaaa** [b04rdr1d3r/Mosquito-Streamdeck-profile-for-DCS-Interface-P#1]
you said 'DCS Export Scripts Mosquito module (included in my fork)'

where?

**Comment by b04rdr1d3r** [comment]
thanks for letting me know. seems this repository is missing a few files at the moment... II can't access the machine on which the files are stored this week, but expect the missing files to be uploaded sometime next week...

**Comment by b04rdr1d3r** [comment]
files have been uploaded. marking issue closed.
